<?php

$rateData = $block->getPriceRate();
$i = 1;

?>

<div class='container'>
    <h3 style="margin-bottom: 10px;">Tỷ giá hối đoái từ Vietcombank vào <?= $block->escapeHtml($rateData->DateTime) ?></h3>
    <table class="rate-table">

        <tbody>
            <?php foreach ($rateData->channel->item as $key => $rate) : ?>
                <tr>
                    <td><?= $i ?></td>
                    <td><?= $block->escapeHtml($rate->title) ?></td>
                    <td><?= $rate->description ?></td>
                    <td><?= $block->escapeHtml($rate->pubDate) ?></td>
                    <td><a href = "<?= $block->escapeHtml($rate->link) ?>" target = '_blank'>link</a></td>
                    <td><?= $block->escapeHtml($rate->guid) ?></td>
                </tr>
            <?php $i++;
            endforeach; ?>
        </tbody>
    </table>
</div>

<script>

</script>